name: bestiapop
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - jinja2
  - netcdf4
  - tqdm
  - requests
  - seaborn
  - s3fs
  - geopandas
  - scikit-learn
  - xarray
  - cartopy
  - tabulate
  - h5netcdf
  - matplotlib
  - numpy
  - coloredlogs
  - pandas
  - scipy
  - pip:
    - bestiapop